// src/pages/Career.vue
<template>
  <q-page class="q-pr-md q-pl-md q-pt-md q-pb-md">
    <div class="q-pa-md">
      <div class="q-gutter-md q-mt-xl column flex-center">
        <q-intersection transition="scale">
          <q-card
            class="my-description q-pa-lg"
            :class="$q.dark.isActive ? 'bg-grey-10' : 'bg-grey-4'"
          >
            <q-stepper
              v-model="step"
              ref="stepper"
              class="flex flex-center"
              :class="$q.dark.isActive ? 'bg-grey-10' : 'bg-grey-4'"
            >
              <q-step
                :name="1"
                title="03/2022"
                done-icon="bi-box-arrow-in-right"
                :done="step > 1"
                style="min-height: 200px"
              >
              </q-step>

              <q-step
                :name="1"
                done-icon="bi-door-closed"
                title="02/2023"
                done-color="red"
                :done="step > 1"
                style="min-height: 200px"
              >
              </q-step>
            </q-stepper>
            <q-card-section>
              <div class="text-h4 text-center q-mb-md">
                Trainee Full-Stack - 8SYS Desenvolvimento de Sistemas LTDA.
              </div>
              <q-separator />
              <div class="text-h6 text-weight-thin text-justify q-mt-md">
                <p class="text-center">
                  I’m working directly on the production and maintenance of the
                  company's WebSite, using HTML5, CSS3, JavaScript with JQuery
                  framework and API with PHP.
                </p>
              </div>
            </q-card-section>
          </q-card>
        </q-intersection>
        <q-intersection transition="scale">
          <q-card
            class="my-description q-mt-xl q-pa-lg"
            :class="$q.dark.isActive ? 'bg-grey-10' : 'bg-grey-4'"
          >
            <q-stepper
              v-model="step"
              ref="stepper"
              class="flex flex-center"
              :class="$q.dark.isActive ? 'bg-grey-10' : 'bg-grey-4'"
            >
              <q-step
                :name="1"
                title="03/2023"
                done-icon="bi-box-arrow-in-right"
                :done="step > 1"
                style="min-height: 200px"
              >
              </q-step>

              <q-step
                :name="1"
                title="Currently"
                done-icon="code"
                :done="step > 1"
                style="max-height: 3000px"
              >
              </q-step>
            </q-stepper>
            <q-card-section>
              <div class="text-h4 text-center q-mb-md">
                Trainee Back-End - QYON Sistemas Inteligentes
              </div>
              <q-separator />
              <div class="text-h6 text-weight-thin q-mt-md">
                <p class="text-center">
                  I am working with ReactJS, VueJS, Python and Java (Spring
                  boot) in some of the company's projects
                </p>
              </div>
            </q-card-section>
          </q-card>
        </q-intersection>
      </div>
    </div>
  </q-page>
</template>

<script>
import { defineComponent, onBeforeMount, ref } from "vue";
import { hideLoading, showLoading } from "src/util/plugins";

export default defineComponent({
  name: "CareerPage",
  setup() {
    onBeforeMount(() => {
      showLoading("Carregando...");
      setTimeout(() => {
        hideLoading();
      }, 100);
    });
    return { slide: ref("first"), step: ref(2) };
  },
});
</script>

// src/components/career/index.jsx
import React, { Component } from 'react'
import { Container, DivTitle, Title, DescCareer, LiCareer, PCareer, DivIcons,Icons } from './styles'
// import html from './images/html.png'
// import css from './images/css.png'
// import Bootstrap from './images/Bootstrap.png'
import JS from './images/JS.png'
import ReactJS from './images/ReactJS.png'
import nodejs from './images/nodejs.png'
import typescript from './images/typescript.png'
import java from './images/java.png'
import python from './images/python.png'
import git from './images/Git.png'
import php from './images/php.png'
// import c from './images/C.png'
// import cSharp from './images/CSharp.png'
// import api from './images/api.png'
import postgresql from './images/postgresql.png'
import mysql from './images/mysql.png'

import FadeInUp from '../../FadeInUp';




export default class Career extends Component {
  render() {
    return (
      <Container>
        <div>
          <FadeInUp duration="0.6s" delay="0.2s">
            <DivTitle>
              <Title>My Career</Title>
            </DivTitle>
          </FadeInUp>
          <DescCareer>
            <ul>
            <FadeInUp duration="0.6s" delay="0.2s">

              <LiCareer>
                Trainee Full-Stack - 8SYS Desenvolvimento de Sistemas LTDA (03/2022 - 02/2023).
              </LiCareer>
              
            </FadeInUp>
            <FadeInUp duration="0.6s" delay="0.2s">

              <PCareer>I’m working directly on the production and maintenance of the company's WebSite, using HTML5, CSS3, JavaScript with JQuery framework and API with PHP.</PCareer>
              
            </FadeInUp>
            
            </ul>

            <ul>
            <FadeInUp duration="0.6s" delay="0.2s">

              <LiCareer>
                Trainee Full-Stack - QYON Sistemas Inteligentes (03/2023 - Currently).
              </LiCareer>
              
            </FadeInUp>
            <FadeInUp duration="0.6s" delay="0.2s">

              <PCareer>I am working with ReactJS, Python, VueJS and Elixir in some of the company's projects</PCareer>
              
            </FadeInUp>
            
            </ul>
          </DescCareer>
        </div>
        <div>
          <FadeInUp duration="0.6s" delay="0.2s">

            <DivTitle>
              <Title>My Skills</Title>
            </DivTitle>

          </FadeInUp>

          <DivIcons>
            <FadeInUp duration="0.6s" delay="0.2s">
              <Icons src={JS}/>
              <Icons src={ReactJS}/>
              <Icons src={nodejs}/>
              <Icons src={typescript}/>
              <Icons src={java}/>
              <Icons src={php}/>
              <Icons src={python}/>
              <Icons src={git}/>
              <Icons src={postgresql}/>
              <Icons src={mysql}/>
            </FadeInUp>
          </DivIcons>
        </div>
      </Container>
    )
  }
}
